version: '2'
services:
    web:
        build: .
        ports:
                - 5000:5000
        depends_on:
            - redis
        networks:
            - app
    redis:
        image: redis
        ports:
                - 6379:6379
        networks: 
            - app
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.1/22








